Experiment_name: K-fold-train-3

# feeder
feeder: feeders.feeder.K_Fold_Feeder
train_feeder_args:
  data_path: ./data/UAV/skeleton/processed/train_data.npy
  label_path: ./data/UAV/skeleton/processed/train_label.pkl
  # data_path: ./data/UAV/skeleton/random_sample/train_data_joint.npy
  # label_path: ./data/UAV/skeleton/random_sample/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False
  flag: train

test_feeder_args:
  data_path: ./data/UAV/skeleton/processed/test_data.npy
  label_path: ''
  # data_path: ./data/UAV/skeleton/random_sample/train_data_joint.npy
  # label_path: ./data/UAV/skeleton/random_sample/train_label.pkl
  # data_path: ./data/UAV/skeleton/random_sample/val_data_joint.npy
  # label_path: ./data/UAV/skeleton/random_sample/val_label.pkl
  # data_path: ./data/UAV/skeleton/processed/train_data.npy
  # label_path: ./data/UAV/skeleton/processed/train_label.pkl
  debug: False
  # flag: val
  flag: test

# model
model: model.shift_gcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0,1,2,3]
only_train_epoch: 1
batch_size: 32
test_batch_size: 1
num_epoch: 140
nesterov: True