Experiment_name: ntu_ShiftGCN_joint_xview # 实验名称，及保存log、model的目录名

# feeder
feeder: feeders.feeder.Feeder   # Dataloader名
train_feeder_args:  # Train的配置
  data_path: ./data/NTU-RGBD/ntu/xview/train_data_joint.npy # 训练数据文件
  label_path: ./data/NTU-RGBD/ntu/xview/train_label.pkl # 测试数据文件
  debug: False  # 是否进行debug
  random_choose: False  # 是否采用随机采样进行增强
  random_shift: False   # 是否采用shift平移
  random_move: False    # 是否移动
  window_size: -1       # 局部shift的窗口设置
  normalization: False  # 是否进行归一化

test_feeder_args:
  data_path: ./data/NTU-RGBD/ntu/xview/val_data_joint.npy
  label_path: ./data/NTU-RGBD/ntu/xview/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60   # 动作类别数
  num_point: 25   # 关节点数
  num_person: 2   # 视野中人数
  graph: graph.ntu_rgb_d.Graph  # 结构图
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 140
nesterov: True